[project]
name = "latex_generator"
version = "0.1"
description = "A library for generating LaTeX code."
authors = [
    { name = "Liliia Imamutdinova", email = "lilyreber404@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
]

